name: CI Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  test_renderer:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/RendererTests/
   
    - name: Test Renderer
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
      working-directory: ./src/RendererTests/
 
    - name: Coveralls Renderer
      uses: coverallsapp/github-action@master
      with:
        parallel: true
        parallel-finished: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./src/RendererTests/lcov.info
        
  test_crispy_viewer:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/RendererTests/
   
    - name: Test Renderer
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info
      working-directory: ./src/RendererTests/
 
    - name: Coveralls Renderer
      uses: coverallsapp/github-action@master
      with:
        parallel: true
        parallel-finished: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./src/RendererTests/lcov.info

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/
